# ===============================
# H2 DATABASE
# ===============================
spring.datasource.url=jdbc:h2:mem:mtcombustiveis
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=adm
spring.datasource.password=adm

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# SERVER
# ===============================
server.port=8080
# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# JPA
spring.jpa.open-in-view=false